services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketflow-rabbitmq
    ports:
      - "5672:5672"    # AMQP — usado por los microservicios
      - "15672:15672"  # Management UI — http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    container_name: ticketflow-mailhog
    ports:
      - "1025:1025"   # SMTP — usado por notification-service
      - "8025:8025"   # Web UI — http://localhost:8025

volumes:
  rabbitmq_data:
